configuration: Release

init:
  - cmd: set
  
install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - cmd: nuget install GitVersion.CommandLine -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre
  - cmd: nuget install gitlink -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre 
  
before_build:
  - cmd: nuget restore
  - cmd: '.\packages\GitVersion.CommandLine\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo'
  
build_script:
  - cmd: 'msbuild MetroLog.sln /m /p:platform="Mixed Platforms" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'
  
after_build:
  - cmd: '.\packages\gitlink\lib\net45\GitLink.exe . -f MetroLog.sln -u https://github.com/onovotny/metrolog -s %APPVEYOR_REPO_COMMIT% -errorsaswarnings'
  - cmd: nuget pack MetroLog.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -NoPackageAnalysis
  - cmd: appveyor PushArtifact "MetroLog.%GitVersion_NuGetVersion%.nupkg"
  
test:
  assemblies:
    - '**\metrolog.tests.dll'